### ISSUE TITLE
Pyannote now only segments half of an audio file

### ISSUE THREAD

**Issue by altunenes** [thewh1teagle/pyannote-rs#14]
I think I broke something with the last ort update sorry :( 

At first I wondered if it was my own audio pipelines, but when I tried [this](https://github.com/thewh1teagle/pyannote-rs/blob/main/examples/infinite.rs) example directly (without change anything), I only got this output 

start = 0.79, end = 4.03, speaker = 1
start = 4.03, end = 8.87, speaker = 1
start = 8.87, end = 17.14, speaker = 2
start = 17.14, end = 18.95, speaker = 3
start = 18.95, end = 19.76, speaker = 4

but "6_speakers.wav" lasts 40 seconds actually.

**Comment by altunenes** [comment]
added some debugs to understand cause of this 


https://github.com/thewh1teagle/pyannote-rs/blob/230af1ba389ad6699090c3b5a70cce32a2f5c5e5/src/segment.rs#L83

```rust
            println!("Total samples: {}", samples.len());
            println!("Total padded samples: {}", padded_samples.len());
            println!("Processing window: {} to {}", start, end);
            println!("Processed output tensor shape: {:?}", ort_out.shape());
            println!("Window size: {}", window_size);
            println!(
                "Current window: {} to {} (length: {})",
                start,
                end,
                window.len()
            );
            println!("Tensor shape: {:?}", ort_out.shape());
            println!("Number of outer iterations: {}", ort_out.outer_iter().len());
```
Processed output tensor shape: [1, 589, 7]
Tensor shape: [1, 589, 7]
Number of outer iterations: 1

Tensor shapes are consistent. But after debugging, The interesting part is that the last detected segment ends at 19.76 seconds, while with 651,603 samples at 16kHz, the audio should be about 40.7 seconds long (651603/16000 ≈ 40.7) which is the current problem . Why??? 😭😭

**Comment by thewh1teagle** [comment]
This commit cause the issue 15f94ff19778a4ca34caa798e27cff1197981721 :\

**Comment by thewh1teagle** [comment]
I guess something with the state of the iterator is not working well. Iterators are sucks in Rust
